org: blackgecko
app: demesne
service: demesne

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: "20201221"
  region: ap-southeast-2

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
